#!/usr/bin/env python3
"""Assets for the DR11-campaign report's 'residual robustness' subsection:
  (1) figures/residual_robustness.png -- DESI grz / legacy-residual / honest-chi-residual for 3
      confirmed candidates (shows the legacy Gaussian high-pass butterfly artifact vs the honest
      signed-chi residual on the SAME bright lens galaxies).
  (2) residual_summary_table.tex   -- the 3-arm cascade summary (PRIOR / LEG-now / NEW).
  (3) residual_tracking_table.tex  -- the 24 confirmed A/B systems tracked across all 3 arms.
All numbers come from the three cascade parquets so the report and the data cannot drift.

Run (lensjudge venv):
  PYTHONPATH=<reproductions> /home2/benson/.venvs/lensjudge/bin/python dr11-campaign/make_residual_robustness_assets.py
"""
import os
import sys
from pathlib import Path
import numpy as np
import pandas as pd

D = Path("/home2/benson/git/agentic-lensing/reproductions")
sys.path.insert(0, str(D))
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from lensjudge.common import render, fetch

LJ = D / "lensjudge"
CAMP = D / "dr11-campaign"
PAP = CAMP / "papers"
FIG = PAP / "figures"
DATA = CAMP / "data"
AB = {"A", "B"}

ARMS = {
    "PRIOR": LJ / "outputs" / "dr11s_cascade_full.parquet",
    "LEG":   LJ / "outputs" / "dr11s_cascade_full_legacy_now.parquet",
    "NEW":   LJ / "outputs" / "dr11s_cascade_full_resid2.parquet",
}
dfs = {k: pd.read_parquet(p).assign(name=lambda d: d["name"].astype(str)).set_index("name")
       for k, p in ARMS.items()}

# ---------------- (1) figure: legacy vs honest residual on the same candidates ----------------
def residual_view(cube, ver):
    os.environ["LENSJUDGE_RESIDUAL_VERSION"] = ver          # read at call time by render.residual_version()
    return render.render_views(cube, views=["residual"])["residual"]

cands = ["s_340513_3688", "s_327526_9059", "s_326089_1785"]   # confirmed NEW-class, bright LRG lenses
labels = {"s_340513_3688": "s\\_340513\\_3688 (A, clear arc)",
          "s_327526_9059": "s\\_327526\\_9059 (A, new)",
          "s_326089_1785": "s\\_326089\\_1785 (B, new)"}
ncol = 3
fig, axes = plt.subplots(len(cands), ncol, figsize=(5.2 * 2.05, len(cands) * 2.45),
                         gridspec_kw={"width_ratios": [1, 1, 3]})
axes = np.atleast_2d(axes)
coltitles = ["DESI $grz$ (0.262″/px)",
             "legacy residual\n(Gaussian high-pass)",
             "honest $\\chi$ residual  $g\\,|\\,r\\,|\\,z$  (signed, noise-normalised; red = excess/arc, blue = over-subtraction)"]
for a in axes.flat:
    a.set_xticks([]); a.set_yticks([])
for j, t in enumerate(coltitles):
    axes[0, j].set_title(t, fontsize=9)
for i, nm in enumerate(cands):
    p = fetch.on_disk_path(nm, "dr11")
    cube = render.load_cube(p) if p is not None else None
    if cube is None:
        print(f"  WARN no cube for {nm}"); continue
    full = np.asarray(render.lupton(cube))
    leg = np.asarray(residual_view(cube, "legacy"))
    new = np.asarray(residual_view(cube, "new"))
    axes[i, 0].imshow(full, origin="upper")
    axes[i, 0].set_ylabel(nm.replace("_", "\\_"), fontsize=8)
    axes[i, 1].imshow(leg, origin="upper")
    axes[i, 2].imshow(new, origin="upper")
    print(f"  {nm}: full{full.shape} legacy{leg.shape} new{new.shape}")
fig.subplots_adjust(left=0.04, right=0.995, top=0.93, bottom=0.01, wspace=0.04, hspace=0.08)
out = FIG / "residual_robustness.png"
fig.savefig(out, dpi=200); plt.close(fig)
print(f"wrote {out}")

# ---------------- (2) 3-arm summary table ----------------
def stats(d):
    t2 = d["highres_survey"].notna()
    g = d["grade_pred"]
    return dict(
        tier2=int(t2.sum()),
        t2ab=int((t2 & g.isin(AB)).sum()),
        rawab=int(g.isin(AB).sum()),
        A=int((g == "A").sum()), B=int((g == "B").sum()),
        C=int((g == "C").sum()), Dd=int((g == "D").sum()),
        cost=float(d["cost_usd"].sum()),
    )
S = {k: stats(v) for k, v in dfs.items()}
rowlabel = {"PRIOR": "Prior (legacy, Jun-17)", "LEG": "Legacy-now (control)", "NEW": "\\textbf{New ($\\chi$ residual)}"}
lines = []
for k in ("PRIOR", "LEG", "NEW"):
    s = S[k]
    lines.append(f"{rowlabel[k]} & {s['tier2']} & {s['t2ab']} & {s['rawab']} & "
                 f"{s['A']}/{s['B']}/{s['C']}/{s['Dd']} & \\${s['cost']:.2f} \\\\")
summary = (
    "% auto-generated by make_residual_robustness_assets.py\n"
    "\\begin{table}[t]\\centering\n"
    "\\caption{Paired residual A/B on the same 500 DR11-south candidates: the prior (legacy) vetting "
    "run, a legacy-residual rerun (the LLM-nondeterminism control), and the new honest-$\\chi$-residual "
    "run. The honest residual runs $\\sim$2$\\times$ hotter at the DESI tier-1 grade (raw A/B "
    f"{S['LEG']['rawab']}$\\to${S['NEW']['rawab']}) but the HSC tier-2 gate absorbs it, so the "
    f"confirmed catalogue (tier-2 A/B) is stable ({S['PRIOR']['t2ab']}/{S['LEG']['t2ab']}/{S['NEW']['t2ab']}).}}\n"
    "\\label{tab:residab}\n"
    "\\begin{tabular}{lccccc}\n\\toprule\n"
    "run & reached & tier-2 & raw A/B & grade & cost \\\\\n"
    " & HSC tier-2 & A/B & (all 500) & A/B/C/D & \\\\\n\\midrule\n"
    + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
)
(PAP / "residual_summary_table.tex").write_text(summary)
print("wrote residual_summary_table.tex")

# ---------------- (3) 24-system tracking table ----------------
conf = pd.read_csv(DATA / "dr11s_confirmed_AB.csv").astype({"name": str})
# order by PRIOR p_lens desc to match Table 2 ordering feel
def grp(d, nm):
    if nm in d.index:
        return d.loc[nm, "grade_pred"], float(d.loc[nm, "p_lens"])
    return "--", float("nan")
conf["_p"] = [grp(dfs["PRIOR"], n)[1] for n in conf["name"]]
conf = conf.sort_values("_p", ascending=False)
trows = []
n_new_surv = n_new = n_sug_surv = n_sug = 0
for _, r in conf.iterrows():
    nm = r["name"]; cls = r.get("class", "?")
    cells = []
    for k in ("PRIOR", "LEG", "NEW"):
        g, p = grp(dfs[k], nm)
        cells.append(f"{g}/{p:.2f}" if g != "--" else "--")
    surv = grp(dfs["NEW"], nm)[0] in AB
    mark = "" if surv else "$^{\\downarrow}$"
    clstag = "\\textsc{new}" if cls == "NEW" else "SuGOHI"
    if cls == "NEW":
        n_new += 1; n_new_surv += int(surv)
    else:
        n_sug += 1; n_sug_surv += int(surv)
    nm_tex = nm.replace("_", "\\_")
    trows.append(f"\\texttt{{{nm_tex}}}{mark} & {clstag} & {cells[0]} & {cells[1]} & {cells[2]} \\\\")
track = (
    "% auto-generated by make_residual_robustness_assets.py\n"
    "\\begin{table}[t]\\centering\\small\n"
    "\\caption{The 24 confirmed tier-2 grade-A/B systems tracked across the three residual arms "
    "(grade\\,/\\,$p_{\\rm lens}$). \\textbf{All "
    f"{n_new_surv}/{n_new} \\textsc{{new}}-class campaign discoveries survive as A/B under the honest "
    f"residual}}; {n_sug_surv}/{n_sug} SuGOHI cross-matches do likewise. $^{{\\downarrow}}$ marks the "
    "two SuGOHI lenses the honest grader scores below A/B (one already lost to nondeterminism in the "
    "legacy-now control); both are independently-confirmed lenses, i.e.\\ conservative grading, not "
    "campaign candidates.}\n"
    "\\label{tab:residtrack}\n"
    "\\begin{tabular}{llccc}\n\\toprule\n"
    "name & class & prior & legacy-now & new ($\\chi$) \\\\\n\\midrule\n"
    + "\n".join(trows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
)
(PAP / "residual_tracking_table.tex").write_text(track)
print(f"wrote residual_tracking_table.tex  (NEW survive {n_new_surv}/{n_new}, SuGOHI {n_sug_surv}/{n_sug})")
print("done")
