#!/usr/bin/env python3
"""Generate the top-100 longtable for the paper appendix.

Usage: make_appendix_table.py /path/to/jwst-strong-lens-search /path/to/papers
Writes table_top100.tex (a longtable body, \\input into main.tex).
"""
import csv
import os
import sys

REPO, PAPERS = sys.argv[1], sys.argv[2]

try:
    import pandas as pd
    tgt = pd.read_parquet(os.path.join(REPO, "data", "targets.parquet"))
    exp = {r.id: (r.sw_exptime, r.lw_exptime) for r in tgt.itertuples()}
except Exception:
    exp = {}

with open(os.path.join(REPO, "results", "JWST_top100_master.csv")) as f:
    rows = list(csv.DictReader(f))
era = {}
with open(os.path.join(REPO, "results", "einstein_radii.csv")) as f:
    for r in csv.DictReader(f):
        era[r["id"]] = (r["theta_E_arcsec"], r["theta_E_err_arcsec"])

STATUS = {"known": "published", "new": "none found", "field_match": "field",
          "possible": "possible"}


def tex(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


out = []
out.append(r"% Auto-generated by assets/analysis/make_appendix_table.py — do not edit.")
out.append(r"\begin{scriptsize}")
out.append(r"\setlength{\tabcolsep}{2pt}")
out.append(r"\begin{longtable}{@{}rlllcccclc@{}}")
out.append(r"\caption{The top-100 candidate list. $\theta_{\mathrm{E}}$ is the blind"
           r" geometric estimate (arc radius or half image-separation) measured from"
           r" the imaging alone; grades: A = passed all three adversarial verifiers,"
           r" B = two, C = one, U = flagged but not selected for verification."
           r" ``Prior ID'' is the run's own literature verdict; the independent audit"
           r" (Section~\ref{sec:results-xmatch}) further reclassifies 24 rows as"
           r" cluster-field matches. Exposure time is the SW-filter total.}"
           r"\label{tab:top100}\\")
out.append(r"\toprule")
hdr = (r"\# & ID & RA, Dec (J2000) & Grade & $\theta_{\mathrm{E}}$ ($''$) & "
       r"$z_{\rm ph}$ & $z_{\rm sp}$ & Filters & $t_{\rm exp}$ (ks) & Prior ID\\")
out.append(hdr)
out.append(r"\midrule")
out.append(r"\endfirsthead")
out.append(r"\toprule")
out.append(hdr)
out.append(r"\midrule")
out.append(r"\endhead")
out.append(r"\midrule \multicolumn{10}{r}{\emph{continued}}\\ \bottomrule")
out.append(r"\endfoot")
out.append(r"\bottomrule")
out.append(r"\endlastfoot")

for r in rows:
    rank = r["rank"]
    cid = tex(r["candidate_id"])
    coords = f"{r['ra_sex']}, {r['dec_sex']}"
    grade = r["verifier_grade"]
    te, tee = era.get(r["candidate_id"], ("", ""))
    if te:
        try:
            tstr = f"{float(te):.2f}$\\pm${float(tee):.2f}"
        except ValueError:
            tstr = te
    else:
        tstr = "--"
    zph = r["deflector_z_phot"]
    zph = f"{float(zph):.3f}" if zph.strip() else "--"
    zsp = r["deflector_z_spec"]
    zsp = f"{float(zsp):.4f}" if zsp.strip() else "--"
    filt = f"{r['sw_filter']}/{r['lw_filter']}".strip("/") or "--"
    e = exp.get(r["candidate_id"])
    tex_exp = f"{e[0] / 1000:.1f}" if e and e[0] == e[0] else "--"
    status = STATUS.get(r["discovery_status"], r["discovery_status"])
    out.append(f"{rank} & {cid} & {coords} & {grade} & {tstr} & {zph} & {zsp} & "
               f"{tex(filt)} & {tex_exp} & {status}\\\\")

out.append(r"\end{longtable}")
out.append(r"\end{scriptsize}")

with open(os.path.join(PAPERS, "table_top100.tex"), "w") as f:
    f.write("\n".join(out) + "\n")
print("wrote", os.path.join(PAPERS, "table_top100.tex"), f"({len(rows)} rows)")
