#!/usr/bin/env python
"""20_build_zoo.py -- materialize the lens-posterior zoo and write THE freeze.

For every available registry target: build it, evaluate log_prob at 3 fixed
seeded reference z-points (cgl.zoo.runtime.make_freeze_points; the z values
are stored EXPLICITLY, never regenerated by readers), and record
values+hashes+dims+dtype+labels to data/zoo_freeze.json. Benchmark cells
(22_run_cell.py) and adapters assert against this freeze before any run.

dtype discipline: one process cannot mix x64 states, so the default
(orchestrator) mode spawns ONE SUBPROCESS PER TARGET with GIGALENS_X64 set
from the registry's static dtype; workers write data/zoo_freeze.parts/*.json
which the orchestrator merges.

Run (GPU 9, the campaign L4):
  /raid/benson/.venvs/cgl/bin/python 20_build_zoo.py            # all targets
  /raid/benson/.venvs/cgl/bin/python 20_build_zoo.py --targets t0_mix2 ...
  ... 20_build_zoo.py --worker gu2022_sys000                    # internal
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

REPRO = Path(__file__).resolve().parent
WORKER_TIMEOUT_S = 2400


def parse_args():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--targets", nargs="*", default=None,
                    help="registry names (default: all available)")
    ap.add_argument("--worker", default=None, help="internal: build ONE "
                    "target in this process and write a freeze part")
    ap.add_argument("--gpu", default=None, help="CUDA index (default 9)")
    return ap.parse_args()


# --------------------------------------------------------------------------- #
# worker: one target, one process
# --------------------------------------------------------------------------- #
def run_worker(name: str, gpu):
    from cgl.zoo import get_target_info
    from cgl.zoo.runtime import setup_process_env

    info = get_target_info(name)
    setup_process_env(info.dtype, gpu)          # BEFORE jax import

    import jax  # noqa: E402

    from cgl.zoo import get_target
    from cgl.zoo.api import sha256_array, sha256_labels
    from cgl.zoo.runtime import make_freeze_points, setup_jax_cache

    setup_jax_cache(REPRO)
    import numpy as np

    print(f"[worker {name}] devices={jax.devices()} "
          f"x64={jax.config.jax_enable_x64}", flush=True)
    t0 = time.time()
    target = get_target(name)
    t_build = time.time() - t0

    pts = make_freeze_points(target)                       # (3, dim)
    t0 = time.time()
    fdtype = np.float64 if target.dtype == "float64" else np.float32
    logp = np.asarray(target.log_prob_batch(pts.astype(fdtype)),
                      dtype=np.float64)
    # batch-vs-single consistency at point 0 (jit fusion sanity)
    lp0 = float(np.asarray(target.log_prob(pts[0].astype(fdtype))))
    t_eval = time.time() - t0
    assert np.all(np.isfinite(logp)), f"non-finite freeze logp: {logp}"

    dev = jax.devices()[0]
    entry = dict(
        name=name, tier=target.tier, dim=int(target.dim), dtype=target.dtype,
        noise_model=target.noise_model,
        labels=list(target.labels),
        labels_sha256=sha256_labels(target.labels),
        mass_labels=list(target.mass_labels),
        points=[
            dict(index=k,
                 z=pts[k].tolist(),
                 z_sha256=sha256_array(pts[k]),
                 logp=float(logp[k]),
                 logp_hex=np.float64(logp[k]).tobytes().hex(),
                 logp_sha256=sha256_array(np.array([logp[k]])))
            for k in range(pts.shape[0])
        ],
        batch_vs_single_abs_diff_p0=abs(float(logp[0]) - lp0),
        init=dict(
            has_map_z=target.init.map_z is not None,
            has_svi=target.init.svi_scale_tril is not None,
            svi_n_floored=int(target.init.svi_n_floored),
            has_hess_diag_raw=target.init.hess_diag_raw is not None,
            n_multi_starts=(0 if target.init.multi_starts is None
                            else int(target.init.multi_starts.shape[0])),
            notes=target.init.notes),
        reference=(None if target.reference is None else dict(
            provenance=target.reference.provenance,
            logZ=target.reference.logZ,
            mode_labels=(None if target.reference.mode_labels is None
                         else list(target.reference.mode_labels)),
            mode_weights=(None if target.reference.mode_weights is None
                          else np.asarray(
                              target.reference.mode_weights).tolist()),
            mode_weights_trusted=target.reference.mode_weights_trusted,
            caveats=target.reference.caveats)),
        meta=target.meta,
        build_s=t_build, eval_s=t_eval,
        env=dict(device=str(dev), device_kind=dev.device_kind,
                 x64=bool(jax.config.jax_enable_x64),
                 jax=jax.__version__),
    )

    from cgl.paths import ZOO_FREEZE_PARTS
    ZOO_FREEZE_PARTS.mkdir(parents=True, exist_ok=True)
    out = ZOO_FREEZE_PARTS / f"{name}.json"
    out.write_text(json.dumps(entry, indent=2))
    print(f"[worker {name}] dim={target.dim} dtype={target.dtype} "
          f"logp={[f'{v:.6f}' for v in logp]} "
          f"(build {t_build:.1f}s, eval {t_eval:.1f}s) -> {out}", flush=True)
    return 0


# --------------------------------------------------------------------------- #
# orchestrator: subprocess per target, then merge
# --------------------------------------------------------------------------- #
def run_orchestrator(names, gpu):
    from cgl.paths import ZOO_FREEZE, ZOO_FREEZE_PARTS
    from cgl.zoo import get_target_info, list_targets
    from cgl.zoo.runtime import child_env

    if not names:
        names = [t["name"] for t in list_targets(available_only=True)]
    print(f"freezing {len(names)} targets: {names}", flush=True)

    failures = {}
    for name in names:
        info = get_target_info(name)
        if not info.available:
            print(f"[skip] {name}: unavailable ({info.note})", flush=True)
            continue
        cmd = [sys.executable, str(Path(__file__).resolve()),
               "--worker", name]
        if gpu is not None:
            cmd += ["--gpu", str(gpu)]
        print(f"[spawn] {name} (dtype {info.dtype}) ...", flush=True)
        t0 = time.time()
        r = subprocess.run(cmd, env=child_env(info.dtype, gpu),
                           timeout=WORKER_TIMEOUT_S)
        print(f"[done ] {name} rc={r.returncode} ({time.time()-t0:.0f}s)",
              flush=True)
        if r.returncode != 0:
            failures[name] = r.returncode

    parts = {}
    for name in names:
        p = ZOO_FREEZE_PARTS / f"{name}.json"
        if p.exists():
            parts[name] = json.loads(p.read_text())

    freeze = dict(
        generated_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        freeze_seed0=20260706,
        n_points=3,
        point_rule="z_k = anchor + scale*default_rng(seed0+k).standard_normal"
                   "(dim); anchor=init.map_z scale=0.1 if map_z else 0/0.5; "
                   "values stored explicitly -- assert against 'z', never "
                   "regenerate",
        tolerance=dict(float64=1e-10, float32=1e-6,
                       note="max rel |dlogp| for freeze re-checks on the same "
                            "device class (L4)"),
        n_targets=len(parts),
        targets=parts,
        failures=failures,
    )
    ZOO_FREEZE.parent.mkdir(parents=True, exist_ok=True)
    ZOO_FREEZE.write_text(json.dumps(freeze, indent=2))
    print(f"\nwrote {ZOO_FREEZE} ({len(parts)} targets, "
          f"{len(failures)} failures)", flush=True)
    for name, e in sorted(parts.items()):
        print(f"  {name:16s} {e['tier']} dim={e['dim']:3d} {e['dtype']:8s} "
              f"logp0={e['points'][0]['logp']:+.6f}", flush=True)
    if failures:
        print(f"FAILURES: {failures}", flush=True)
        return 1
    return 0


def main():
    args = parse_args()
    if args.worker:
        return run_worker(args.worker, args.gpu)
    return run_orchestrator(args.targets, args.gpu)


if __name__ == "__main__":
    sys.exit(main())
